services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - /Users/olemerdy/.ollama
#  cassandra:
#    image: cassandra
#    ports:
#      - "7000:7000"
#      - "9042:9042"