spring:
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        chat:
          additional-models:
            - llama3.2
#    vectorstore:
#      cassandra:
#        initialize-schema: true